# Site settings
author: Brianna J
title: The Dev Experience
header-img: img/home-bg.png
email: bryvjordan9@gmail.com
copyright_name: Brianna J
description: > # this means to ignore newlines until "baseurl:"
  Views and advancements of a Developer 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: BriJaySay
github_username:  byjord10

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
